// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5JDipKZ9q6A-jWndkYX9f7k_3YUp72PA',
    appId: '1:544554279146:web:11d771ca0fadc6b6fdb793',
    messagingSenderId: '544554279146',
    projectId: 'flutter-study-app-a1c02',
    authDomain: 'flutter-study-app-a1c02.firebaseapp.com',
    storageBucket: 'flutter-study-app-a1c02.appspot.com',
    measurementId: 'G-3B9Q09NS19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0py5kHsaaDoxUH3dwl42rlrQarq1N8DM',
    appId: '1:544554279146:android:2c092133db12a9c1fdb793',
    messagingSenderId: '544554279146',
    projectId: 'flutter-study-app-a1c02',
    storageBucket: 'flutter-study-app-a1c02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB54ZIjYGHlfkqiWhQzhZ_XioubDe-c040',
    appId: '1:544554279146:ios:c35348cfd8409a6afdb793',
    messagingSenderId: '544554279146',
    projectId: 'flutter-study-app-a1c02',
    storageBucket: 'flutter-study-app-a1c02.appspot.com',
    iosBundleId: 'com.example.flutterStudyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB54ZIjYGHlfkqiWhQzhZ_XioubDe-c040',
    appId: '1:544554279146:ios:c35348cfd8409a6afdb793',
    messagingSenderId: '544554279146',
    projectId: 'flutter-study-app-a1c02',
    storageBucket: 'flutter-study-app-a1c02.appspot.com',
    iosBundleId: 'com.example.flutterStudyApp',
  );
}
